### ISSUE TITLE
Opinion wanted: Whether project templates should be nearly empty code

### ISSUE THREAD

**Issue by kekyo** [kekyo/Epoxy#29]
Usually, the templates generated by the wizards are quite simplistic, such as simply displaying a window. As you know, Epoxy includes code that accesses Reddit to download and display images.

This sample code was created to show that the code equivalent to the Model in MVVM can be completely separated from the View and ViewModel, and can be implemented in this way in Epoxy.
However, when I myself started writing code in Epoxy, I had to delete this Reddit accessor code and the code related to the image viewer placed in the View every single time, which I found troublesome.

Therefore, I think it would be better to place the sample code to access Reddit in another directory in this repository (it might be OK to leave the current sample directory as it is now), and to include only the pure code in the Templates package.

I am also wondering if we should include a Model project, since doing this would eliminate the need for a Model project implementation. I would prefer to have an empty Model project generated, but it may not be clear to a novice why this is necessary just by looking at it.

Welcome leave a comment if you have any suggestions.

**Comment by sappho192** [comment]
I think it's a good idea to move the sample code (Reddit) to somewhere else and provide pure code as a template, because both can equally help people to easily learn this library.

Can you give me more explanation about Model project? I also wonder why it is necessary to be provided as a template project.

**Comment by kekyo** [comment]
> Can you give me more explanation about Model project? I also wonder why it is necessary to be provided as a template project.

Ya, Epoxy also has a goal of providing relief to users who have migrated from Windows Forms. I believe that these users can easily fall into the trap of relying on a code-behind architecture and not knowing how to get out of it (at least, I have people around me who are stuck with this problem and cannot get out of it).

Also, in the early days of WPF (when Prism was not yet well known), MVVM was discussed only in terms of architectural aspects and dogma, and as a result was misunderstood, resulting in the lack of good and concise documentation (this was especially true in Japan, and I do not understand if this is a worldwide problem.)

So, we decided to have the Epoxy template speak to the role of MVVM, especially the "Model", in code.

Once the purpose of this issue is accomplished, the code for "Model" disappears completely. This would result in a completely meaningless project (and one that does not even reference Epoxy package!), the significance of "Model" is completely lost from the template.

Well, I guess that's OK, since the sample code project still contains code written in MVVM (and I'm beginning to think that's not a problem :)

**Comment by sappho192** [comment]
Well, for me, that sounds very interesting in that I also have a shallow understanding of the model. 
Personally I hope the Model project to be released as suggested! :)

**Comment by kekyo** [comment]
Epoxy 1.10.0 has released. It contains purely clean boiler-plate template code. It has only showing "Hello Epoxy!" text!
