### ISSUE TITLE
Suggestion on replacing the word "Moore" with "Bind" or else

### ISSUE THREAD

**Issue by sappho192** [kekyo/Epoxy#30]
Hello kekyo, thank you always for providing and maintaining such a nice library.

Sometimes I meet the exception message like "Didn't moore a UIElement." when I forgot to bind the UI element with the corresponding Pile object.
At first, I googled the message couldn't find any informations regarding this, so I thought the message may be from this library, and I was right. 

https://github.com/kekyo/Epoxy/blob/8e80c8535714fed8fa4bea68724d88b6d8ab480a/src/Epoxy.Core/Anchor.cs#L256

It seems "**Moore**" seems to be meant as "loosely bind something" because following function is charge of such a task, but AFAIK the word moore is just a noun stands for a name and doesn't have meaning as a verb.

https://github.com/kekyo/Epoxy/blob/8e80c8535714fed8fa4bea68724d88b6d8ab480a/src/Epoxy.Core/Anchor.cs#L222

So I suggest two things to intuitively understand the role of this method and the exception message:

1. Replace `Moore` to `Bind` or `LooselyBind` or `WeakBind` or else
2. Replace the exception message `Didn't moore a UIElement` like `You should bind a UIElement before renting from the Pile.`

Thank you.

**Comment by kekyo** [comment]
I think it is an appropriate suggestion (I can't remember why I used the word Moore :)
I'll apply it on my next fix, thank you!

**Comment by sappho192** [comment]
Thank you too. Have a nice day 😊

**Comment by kekyo** [comment]
Changed these messages, will include in future release 1.11.0.
Thank you your advice!

**Comment by sappho192** [comment]
Thank you too, Kekyo!
Have a nice day ☺
