### ISSUE TITLE
Cause didn't update binding value on FlashCap.Avalonia sample using Epoxy.

### ISSUE THREAD

**Issue by kekyo** [kekyo/Epoxy#34]
Reported in FlashCap repo issue https://github.com/kekyo/FlashCap/issues/46

**Comment by yangjieshao** [comment]
Specifically, when the mouse is **held down on the window title bar**,  didn't update binding value

**Comment by yangjieshao** [comment]
看上去 这是 Avalonia 的问题
(It seems like this is Avalonia's issues)
https://github.com/AvaloniaUI/Avalonia/issues/11322

**Comment by kekyo** [comment]
Once closed, as noted in the FlashCap issue, if it is determined that there is no problem with Avalonia, we will reopen this issue as needed.
