### ISSUE TITLE
Is it possible to use FSharp.Epoxy.Avalonia in cross-platform Avalonia projects?

### ISSUE THREAD

**Issue by shanoaice** [kekyo/Epoxy#35]
It seems like the provided Epoxy Avalonia template only supports desktop workload. Is it possible to use it in a cross-platform Avalonia project? The official Avalonia Cross-platform template does provide F# language support, but I am not sure how to integrate Epoxy with it (and it seems to be using Avalonia v11 too, which I am not sure whether Epoxy has support or not)

**Comment by kekyo** [comment]
@shanoaice Yes, `Fsharp.Epoxy.Avalonia` supports F#. However, the startup sequence included in the template may be a bit outdated and, as noted, only supports the desktop environment.

If you use the latest startup code for Avalonia (e.g. generated from the Avalonia template) and add `FSharp.Epoxy.Avalonia` to it, you should be able to use Epoxy.

(The reason I know this without having tried it is that `FSharp.Epoxy.Avalonia` only references the core Avalonia package :)

I didn't know there was a v11 preview out there! I don't know yet if the packages for 0.10.* can be used for the v11 series, and Epoxy support will likely only address this after the official v11 release. However, if it is strongly desired, we would consider supporting preview packages.

**Comment by kekyo** [comment]
Epoxy 1.10.0 has released, it supports Avalonia 11 and xplat templates botn C# and F#.

(Currently there are unstable in my some building environment. If it turns out that Epoxy is the cause, we will fix it.)
