### ISSUE TITLE
Avalonia11  Events Binding invalid

### ISSUE THREAD

**Issue by cbuduknui** [kekyo/Epoxy#42]
Avalonia version : 11.0.10
Epoxy.Avalonia11 : 1.13.0

<ep:EventBinder.Events>
    <ep:Event Command="{Binding ViewLoaded}" EventName="Loaded" />
</ep:EventBinder.Events>

public string Greeting { get; set; } = "Welcome to Avalonia!";
public Command ViewLoaded { get; }

public MainViewModel()
{
    this.ViewLoaded = Command.Factory.Create(() =>
    {
        Greeting = "Hello!";
        return default;
    });
}

ViewLoaded command not invoke.

**Comment by kekyo** [comment]
Hmm, I don't know what outer control the `MainViewModel` is bound to, could it be `Opened` instead of `Loaded`?

The sample code below is using Epoxy on Avalonia11 and it works as intended:

https://github.com/kekyo/FlashCap/blob/227cca10f66e504cf3abb690fb15fe854da16825/samples/FlashCap.Avalonia/FlashCap.Avalonia.UI/Views/MainWindow.axaml#L21

```xml
    <epoxy:EventBinder.Events>
        <epoxy:Event EventName="Opened" Command="{Binding Opened}" />
    </epoxy:EventBinder.Events>
```

```csharp
        // Window shown:
        this.Opened = Command.Factory.Create(() =>
        {
            // ...
        }
```

**Comment by cbuduknui** [comment]
I am using C# language.
in Window Control using Opened event.
in Usercontrol using Loaded event.
above both event command not invoke.
<epoxy:EventBinder.Events>
        <epoxy:Event EventName="Opened" Command="{Binding ViewLoaded }" />
    </epoxy:EventBinder.Events>

**Comment by kekyo** [comment]
Thanks, I reproduced your problem and will analyze it, please wait!

https://github.com/kekyo/Epoxy.Avalonia11.SampleProject

**Comment by kekyo** [comment]
Being deployed 1.14.0 contains bug fix, could you please test it?

**Comment by cbuduknui** [comment]
Version 1.14.0 is test ok!
